name: Deploy service

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      envName:
        required: true
        type: string
      argo_app_name:
        required: true
        type: string
      namespace:
        required: false
        type: string
        default: "default"
    secrets:
      GH_TOKEN:
        required: true
jobs:
  deploy:
    name: "Deploy version: ${{ inputs.version }} to env: ${{ inputs.envName }}"
    runs-on: ubuntu-20.04
    environment: ${{ inputs.envName }}
    steps:
      - name: Checkout argocd repo
        uses: actions/checkout@v3
        with:
          repository: m10-payments/argocd
          ref: 'main'
          token: ${{ secrets.GH_TOKEN }}
      - name: update ${{ inputs.argo_app_name }} service
        run: |
          echo -n '${{ inputs.version }}' > ./${{ inputs.argo_app_name }}/version-${{ inputs.envName }}.txt
          git config user.name github-actions
          git config user.email github-actions@pashapay.az
          git add ./${{ inputs.argo_app_name }}/version-${{ inputs.envName }}.txt
          git commit --allow-empty -m "chore(release): rollout ${{ inputs.argo_app_name }} version:${{ inputs.version }}"
          git push
