name: Release libjar

#on:
#  push:
#    tags:
#      - v[0-9]+.[0-9]+.[0-9]+

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: resolve input values
        run: |
          echo "inputs_version=${{ inputs.version }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.inputs_version }}
      - name: Get latest Corretto URL
        id: get-latest-corretto-url
        run: >-
          echo "::set-output name=URL::$(curl -LIs -o /dev/null -w
          %{url_effective}
          https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz)"
      - uses: actions/cache@v2
        id: corretto-cache
        name: Restore Corretto
        with:
          path: ./amazon-corretto-17-x64-linux-jdk.tar.gz
          key: ${{ runner.os }}-corretto-${{steps.get-latest-corretto-url.outputs.URL }}
      - name: Download AWS Corretto
        if: steps.corretto-cache.outputs.cache-hit != 'true'
        run: wget https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: jdkfile
          java-version: '17'
          architecture: x64
          jdkFile: ./amazon-corretto-17-x64-linux-jdk.tar.gz
      - name: java version
        run: java --version
      - name: maven version
        run: mvn --version
      - name: test
        run: mvn test
  build:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: resolve input values
        run: |
          echo "inputs_version=${{ inputs.version }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.inputs_version }}

      - name: Get latest Corretto URL
        id: get-latest-corretto-url
        run: >-
          echo "::set-output name=URL::$(curl -LIs -o /dev/null -w
          %{url_effective}
          https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz)"

      - uses: actions/cache@v2
        id: corretto-cache
        name: Restore Corretto
        with:
          path: ./amazon-corretto-17-x64-linux-jdk.tar.gz
          key: ${{ runner.os }}-corretto-${{steps.get-latest-corretto-url.outputs.URL }}

      - name: Download AWS Corretto
        if: steps.corretto-cache.outputs.cache-hit != 'true'
        run: wget https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: jdkfile
          java-version: '17'
          architecture: x64
          jdkFile: ./amazon-corretto-17-x64-linux-jdk.tar.gz

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
