name: Release Helm Chart

on:
  workflow_call:
    inputs:
      chart_name:
        required: true
        type: string
    secrets:
      registry_password:
        required: true

env:
  REGISTRY: "oci://ghcr.io/m10-payments/"

jobs:
  release:
    name: Release Helm Chart ${{ inputs.chart_name }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version from Chart.yaml
        id: chart-version
        run: |
          echo "::set-output name=version::$(helm show chart ${{ inputs.chart_name }} | grep '^version' | awk -F':' '{print $NF}' | sed 's/ //g')"

      - name: Package Helm Chart
        run: |
          helm package ${{ inputs.chart_name }}

      - name: Login to OCI registry
        run: |
          echo ${{ secrets.registry_password }} | helm registry login -u admin-m10 --password-stdin

      - name: Push Helm Chart to remote registry
        env:
          CHART_VERSION: ${{ steps.chart-version.outputs.version }}
        run: |
          helm push ${{ inputs.chart_name }}-${{ env.CHART_VERSION }}.tgz $REGISTRY
